const fs=require('fs'),p='outputs/index.html';let s=fs.readFileSync(p,'utf8');
const pairs=[
['<html lang="en">','<html lang="bn">'],
['content="Root Ritual botanical hair care: considered oils and simple scalp rituals for healthier-looking hair."><title>Root Ritual — Good hair begins beneath the surface</title>','content="রুট রিচুয়ালের ভেষজ চুলের যত্ন—স্ক্যাল্প ও চুলের জন্য যত্নে বেছে নেওয়া তেল আর সহজ দৈনন্দিন রুটিন।"><title>রুট রিচুয়াল — যত্ন শুরু হোক চুলের গোড়া থেকে</title>'],
['https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600&display=swap','https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400;500;600;700&family=Noto+Serif+Bengali:wght@400;500;600;700&display=swap'],
["'Playfair Display',Georgia,serif","'Noto Serif Bengali',serif"],["'DM Sans',Arial,sans-serif","'Noto Sans Bengali',Arial,sans-serif"],
['Good hair begins beneath the surface.','যত্ন শুরু হোক চুলের গোড়া থেকে'],
['A LITTLE RITUAL, A LOT OF LOVE — FREE SHIPPING OVER ৳2,500','একটু যত্ন, অনেকটা ভালোবাসা — ৳২,৫০০-এর বেশি অর্ডারে ডেলিভারি খরচ ফ্রি'],
['root<span>ritual</span>','রুট<span>রিচুয়াল</span>'],
['>Shop</a>','>পণ্য</a>'],['>Ingredients</a>','>উপাদান</a>'],['>Results</a>','>অভিজ্ঞতা</a>'],['>Our story</a>','>আমাদের গল্প</a>'],['>Journal</a>','>যত্নের কথা</a>'],['>Account</button>','>অ্যাকাউন্ট</button>'],['>Bag <span','>ব্যাগ <span'],
['BOTANICAL SCALP CARE · YOUR DAILY RESET','ভেষজ স্ক্যাল্প কেয়ার · আপনার প্রতিদিনের ছোট্ট বিরতি'],['Give your roots a little ritual.','যত্ন শুরু হোক চুলের গোড়া থেকে।'],['A considered botanical oil for scalp and strands. Slow down, massage in, and make wash day feel like care.','স্ক্যাল্প ও চুলের জন্য যত্নে তৈরি ভেষজ তেল। একটু সময় নিয়ে ম্যাসাজ করুন—চুল ধোয়ার দিনটাও হয়ে উঠুক নিজের যত্নের মুহূর্ত।'],['Shop Scalp Elixir&nbsp; →','স্ক্যাল্প এলিক্সির কিনুন&nbsp; →'],['Find your ritual','আমার রুটিন খুঁজুন'],['Find your routine','আমার রুটিন খুঁজুন'],['Root Ritual botanical hair oil bottle','রুট রিচুয়াল স্ক্যাল্প এলিক্সির ভেষজ তেলের বোতল'],
['Plant-forward formulas','উদ্ভিদভিত্তিক যত্ন'],['Made with intention','বেছে নেওয়া উপাদান'],['Easy, everyday rituals','সহজ দৈনন্দিন রুটিন'],['Kind to your routine','যত্ন হোক আপনার মতো'],
['The essentials','যত্নের শুরু'],['Meet your new ritual.','আপনার নতুন যত্নের সঙ্গী'],['Thoughtful formulas, easy to use. Start with one small change and see how your routine feels.','যত্নে তৈরি, ব্যবহারেও সহজ। ছোট্ট একটি পরিবর্তন দিয়ে শুরু করুন—দেখুন আপনার রুটিনে কেমন মানায়।'],
['Rooted in the everyday','প্রতিদিনের যত্নে'],['Care that starts with listening.','যত্নের শুরু আপনার কথা শুনে।'],['We believe a good hair routine should feel like care, not another chore. Root Ritual pairs familiar botanical ingredients with a simple, considered approach to scalp and strand care.','চুলের যত্ন যেন আরেকটি কাজ না হয়ে নিজের জন্য একটু সময় হয়—আমরা তা-ই বিশ্বাস করি। পরিচিত ভেষজ উপাদান আর সহজ, ভেবেচিন্তে সাজানো রুটিনে স্ক্যাল্প ও চুলের যত্ন নেয় রুট রিচুয়াল।'],['Made for real mornings, wash days, and the little moments in between. No miracle claims—just a ritual you can return to.','ব্যস্ত সকাল, চুল ধোয়ার দিন, আর মাঝের ছোট্ট বিরতিগুলোর জন্য। অলৌকিক ফলের প্রতিশ্রুতি নয়—এমন এক যত্ন, যা আপনি নিয়মিত করে যেতে পারবেন।'],['Our point of view','আমাদের গল্প'],['Simple by design','সহজ করে তৈরি'],['Clear routines, helpful guidance.','সহজ রুটিন, কাজে লাগে এমন পরামর্শ।'],['Ingredients with purpose','উদ্দেশ্যপূর্ণ উপাদান'],['Every ingredient earns its place.','প্রতিটি উপাদানের আছে নির্দিষ্ট কাজ।'],['Care over hype','প্রচারের চেয়ে যত্ন'],['Honest expectations, always.','প্রতিশ্রুতিতে থাকি সৎ।'],
['A closer look','উপাদানগুলোকে চিনুন'],['Good things, chosen with care.','যত্ন করে বেছে নেওয়া উপাদান'],['Ingredient details are placeholders pending final formula and substantiation review.','চূড়ান্ত ফর্মুলা ও যাচাই অনুযায়ী উপাদানের তথ্য হালনাগাদ করা হবে।'],['Rosemary','রোজমেরি'],['Aromatic botanical traditionally used in scalp-care rituals.','সুগন্ধি ভেষজ—স্ক্যাল্প কেয়ারের রুটিনে বহুল ব্যবহৃত।'],['Jojoba','জোজোবা'],['A lightweight-feeling plant oil that helps soften dry lengths.','হালকা অনুভূতির উদ্ভিজ্জ তেল, যা শুষ্ক চুলের আগা নরম রাখতে সহায়তা করে।'],['Argan','আরগান'],['Rich, nourishing oil for a smoother, more polished finish.','পুষ্টিকর তেল—চুলকে মসৃণ ও পরিপাটি দেখাতে সহায়ক।'],['Vitamin E','ভিটামিন ই'],["An antioxidant used to help protect the formula's oils.",'ফর্মুলার তেলগুলোকে সুরক্ষায় সহায়তার জন্য ব্যবহৃত অ্যান্টিঅক্সিডেন্ট।'],
['Real routines, real people','আসল রুটিন, আপনাদের গল্প'],['Good hair days, shared.','ভালো চুলের দিনের গল্প'],['Customer stories and before/after imagery should be published only with permission and clear context.','গ্রাহকের গল্প বা আগে-পরে ছবি প্রকাশের আগে সম্মতি ও প্রাসঙ্গিক তথ্য নিশ্চিত করা হবে।'],['My Sunday reset.','রবিবারের নিজের যত্ন।'],['“Feels lovely on my scalp and has made wash day something I look forward to.”','“স্ক্যাল্পে আরামদায়ক লাগে। এখন চুল ধোয়ার দিনটার জন্য অপেক্ষা করি।”'],['Verified purchase','যাচাইকৃত ক্রেতা'],['Just the right amount.','পরিমাণটা একদম ঠিক।'],['“A little goes a long way on my ends. It fits into my routine without fuss.”','“চুলের আগায় অল্প দিলেই যথেষ্ট। ঝামেলা ছাড়াই রুটিনে মানিয়ে গেছে।”'],['Easy to stick with.','নিয়মিত করা সহজ।'],['“The routine card helped me figure out how much to use. Nice, simple product.”','“রুটিন কার্ড দেখে কতটুকু ব্যবহার করব বুঝেছি। সুন্দর, সহজ একটি পণ্য।”'],
['A little community','আমাদের ছোট্ট কমিউনিটি'],['Rituals from your corner.','আপনাদের যত্নের মুহূর্ত'],['Tag <b>@rootritual</b> to share your routine. Images shown are art direction placeholders.','আপনার রুটিনের ছবি শেয়ার করতে <b>@rootritual</b> ট্যাগ করুন। ছবিগুলো নমুনা হিসেবে তৈরি।'],['Wash day, slowed down','চুল ধোয়ার দিনে একটু বিরতি'],['A few drops, that’s all','কয়েক ফোঁটাই যথেষ্ট'],["A few drops, that's all",'কয়েক ফোঁটাই যথেষ্ট'],['Making time for me','নিজের জন্য একটু সময়'],['The Sunday ritual','রবিবারের যত্ন'],
["Not sure where to start?",'কোথা থেকে শুরু করবেন বুঝছেন না?'],["Let's find your hair ritual.",'আপনার চুলের যত্নের রুটিন খুঁজে নিই।'],['A quick, friendly guide to help you choose a starting point.','কোথা থেকে শুরু করবেন—ছোট্ট এই গাইড আপনাকে তা বেছে নিতে সাহায্য করবে।'],['Take the 1-minute quiz ↗','এক মিনিটের কুইজ দিন ↗'],['Kind words','আপনাদের ভালো লাগা'],['From the ritual regulars.','নিয়মিত ক্রেতাদের কথা'],['Write a review','আপনার মতামত লিখুন'],['The bottle looks beautiful on my shelf, and the oil feels lovely before wash day.','“বোতলটা তাকের ওপর দারুণ লাগে, আর চুল ধোয়ার আগে তেলটা ব্যবহার করতেও ভালো লাগে।”'],['The Sunday ritual','রবিবারের যত্ন'],['A little more know-how.','চুলের যত্নে জানুন আরও'],['Explore the journal →','আরও পড়ুন →'],
['The basics · 4 min','প্রাথমিক যত্ন · ৪ মিনিট'],['How to oil your scalp without overdoing it','স্ক্যাল্পে তেল ব্যবহারের সহজ নিয়ম'],['A gentle starting point for finding the amount and frequency that work for you.','কতটুকু তেল, কতবার ব্যবহার করবেন—নিজের জন্য ঠিক মাত্রা খুঁজে নিন।'],['Read the note →','লেখাটি পড়ুন →'],['Ingredients · 5 min','উপাদান · ৫ মিনিট'],['Getting to know the oils in your routine','আপনার রুটিনের তেলগুলোকে চিনুন'],['What a few familiar plant oils can bring to your hair-care ritual.','পরিচিত কয়েকটি উদ্ভিজ্জ তেল কীভাবে চুলের যত্নে কাজে আসে।'],['Rituals · 3 min','দৈনন্দিন যত্ন · ৩ মিনিট'],['A five-minute scalp massage, step by step','পাঁচ মিনিটের স্ক্যাল্প ম্যাসাজ—ধাপে ধাপে'],['A quiet little reset before your next wash day.','পরেরবার চুল ধোয়ার আগে নিজের জন্য একটু বিরতি।'],
['Good to know','জেনে রাখুন'],['Frequently asked.','আপনাদের জিজ্ঞাসা'],['How do I use the Scalp Elixir?','স্ক্যাল্প এলিক্সির কীভাবে ব্যবহার করব?'],['Part hair into sections and apply a few drops directly to the scalp. Massage gently, leave for 30 minutes or overnight if comfortable, then shampoo. Start once weekly and adjust to your needs.','চুল কয়েক ভাগ করে স্ক্যাল্পে কয়েক ফোঁটা দিন। আলতো করে ম্যাসাজ করে ৩০ মিনিট রাখুন; স্বচ্ছন্দ হলে রাতভরও রাখতে পারেন। এরপর শ্যাম্পু করে ধুয়ে ফেলুন। সপ্তাহে একবার দিয়ে শুরু করুন, প্রয়োজনমতো রুটিন ঠিক করুন।'],['Will this make my hair grow?','এটি কি চুল গজাতে সাহায্য করবে?'],['Cosmetic products cannot promise hair growth or treat hair loss. Our oil is designed to condition the scalp and hair. If you have persistent shedding or scalp concerns, speak with a qualified healthcare professional.','প্রসাধনী পণ্য চুল গজানো বা চুল পড়া চিকিৎসার নিশ্চয়তা দিতে পারে না। আমাদের তেল স্ক্যাল্প ও চুলের কন্ডিশনিংয়ের জন্য তৈরি। দীর্ঘদিন চুল পড়লে বা স্ক্যাল্পে সমস্যা থাকলে যোগ্য চিকিৎসকের পরামর্শ নিন।'],['How long does shipping take?','ডেলিভারি পেতে কত দিন লাগে?'],['Placeholder policy: orders typically dispatch in 1–2 business days and arrive in 2–5 business days within Bangladesh. Final shipping terms should be confirmed before launch.','নমুনা নীতিমালা: সাধারণত ১–২ কর্মদিবসে অর্ডার পাঠানো হয়; বাংলাদেশের ভেতরে পৌঁছাতে ২–৫ কর্মদিবস লাগতে পারে। ওয়েবসাইট চালুর আগে চূড়ান্ত ডেলিভারি নীতিমালা নিশ্চিত করুন।'],['Can I return an opened product?','খোলা পণ্য কি ফেরত দেওয়া যাবে?'],['For hygiene, opened products are not eligible for return unless damaged or incorrect. Contact us within 7 days of delivery for help. Replace this with your final policy.','স্বাস্থ্যবিধির কারণে খোলা পণ্য ফেরতযোগ্য নয়—তবে পণ্য ক্ষতিগ্রস্ত বা ভুল হলে ব্যতিক্রম। সহায়তার জন্য ডেলিভারির ৭ দিনের মধ্যে যোগাযোগ করুন। চালুর আগে চূড়ান্ত নীতিমালা বসান।'],['Is it suitable for all hair types?','সব ধরনের চুলে কি ব্যবহার করা যাবে?'],['Hair and scalp needs vary. Our guide offers a starting point, but check the full ingredient list and patch test before first use, especially if you have sensitive skin.','চুল ও স্ক্যাল্পের প্রয়োজন একেকজনের একেক রকম। আমাদের গাইড কেবল শুরু করার পরামর্শ। প্রথম ব্যবহারের আগে সম্পূর্ণ উপাদান তালিকা দেখে প্যাচ টেস্ট করুন—বিশেষ করে ত্বক সংবেদনশীল হলে।'],["Where is my order?",'আমার অর্ডার কোথায়?'],['Use the order tracking link in your confirmation email, or enter your order number and email in our tracking tool.','অর্ডার কনফার্মেশনের ইমেইলে থাকা ট্র্যাকিং লিংক ব্যবহার করুন, অথবা অর্ডার নম্বর ও ইমেইল দিয়ে অর্ডারের অবস্থা দেখুন।'],['Track an order','অর্ডার ট্র্যাক করুন'],
['Explore','ঘুরে দেখুন'],['Shop all','সব পণ্য'],['Our story','আমাদের গল্প'],['Help','সহায়তা'],['FAQs','সাধারণ জিজ্ঞাসা'],['Shipping & returns','ডেলিভারি ও ফেরত'],['Order tracking','অর্ডার ট্র্যাকিং'],['Account & rewards','অ্যাকাউন্ট ও পুরস্কার'],['A note from us','আমাদের চিঠি'],['Occasional rituals, thoughtful notes, and first dibs.','যত্নের টিপস, নতুন খবর আর বিশেষ অফার—মাঝেমধ্যে আপনার ইনবক্সে।'],['Your email address','আপনার ইমেইল ঠিকানা'],['Join us →','সঙ্গে থাকুন →'],['Brand and product details are sample placeholders.','ব্র্যান্ড ও পণ্যের তথ্য নমুনা হিসেবে দেওয়া।'],['Privacy · Terms · Instagram · Contact','গোপনীয়তা · শর্তাবলি · ইনস্টাগ্রাম · যোগাযোগ'],
['Your bag','আপনার ব্যাগ'],['Your bag is waiting for a little ritual.','আপনার ব্যাগে এখনো কোনো পণ্য নেই।'],['Subtotal','সর্বমোট'],['Shipping and taxes calculated at checkout.','ডেলিভারির খরচ পরের ধাপে যোগ হবে।'],['Continue to checkout','চেকআউটে এগিয়ে যান'],['Remove','সরান'],
['Your little corner','আপনার অ্যাকাউন্ট'],['Welcome to Root Ritual.','রুট রিচুয়ালে স্বাগতম।'],['Sign in to view your orders, save your routine, and collect Ritual Points. Account sign-in connects when your store platform is selected.','অর্ডার দেখতে, রুটিন সংরক্ষণ করতে ও রিচুয়াল পয়েন্ট পেতে সাইন ইন করুন। অনলাইন স্টোর চালু হলে অ্যাকাউন্ট ব্যবস্থা যুক্ত হবে।'],['Email address','ইমেইল ঠিকানা'],['you@example.com','আপনার ইমেইল'],['Continue with email','ইমেইল দিয়ে এগিয়ে যান'],['Earn 1 point for every ৳100 spent. 100 points = ৳100 off (sample rewards terms).','প্রতি ৳১০০ কেনাকাটায় ১ পয়েন্ট। ১০০ পয়েন্টে ৳১০০ ছাড় (নমুনা পুরস্কার নীতিমালা)।'],
['Order tracking','অর্ডার ট্র্যাকিং'],["Where's your parcel?",'আপনার পার্সেল কোথায়?'],['Enter your order number and the email used at checkout. Tracking connects when the fulfillment platform is configured.','অর্ডার নম্বর ও কেনাকাটার সময় দেওয়া ইমেইল লিখুন। অর্ডার পাঠানোর ব্যবস্থা যুক্ত হলে ট্র্যাকিং চালু হবে।'],['Order number','অর্ডার নম্বর'],['RR-10482','RR-১০৪৮২'],['Find my order','অর্ডার খুঁজুন'],['Your routine · ','আপনার রুটিন · '],['Your ritual, at a glance.','আপনার যত্নের সহজ পরামর্শ'],['A gentle guide only—your hair and scalp are unique.','এটি কেবল একটি সাধারণ গাইড—আপনার চুল ও স্ক্যাল্পের প্রয়োজন আলাদা হতে পারে।'],['Shop your starting point','আপনার জন্য পণ্যটি দেখুন'],['Keep exploring','আরও ঘুরে দেখুন'],['Secure checkout · Demo','নিরাপদ চেকআউট · নমুনা'],['Almost part of the ritual.','আপনার যত্নের রুটিন আর একটু পরেই।'],['Order subtotal:','অর্ডারের মূল্য:'],['Shipping calculated at the next step.','পরের ধাপে ডেলিভারি খরচ যোগ হবে।'],['Full name','পুরো নাম'],['Your name','আপনার নাম'],['Phone','মোবাইল নম্বর'],['Delivery address','ডেলিভারির ঠিকানা'],['House, street, area','বাড়ি, সড়ক, এলাকা'],['Payment method','পেমেন্ট পদ্ধতি'],['Cash on delivery','ক্যাশ অন ডেলিভারি'],['Mobile payment (configure gateway)','বিকাশ / নগদ (পেমেন্ট ব্যবস্থা যুক্ত হলে চালু হবে)'],['Card (configure gateway)','কার্ড (পেমেন্ট ব্যবস্থা যুক্ত হলে চালু হবে)'],['Place demo order ·','নমুনা অর্ডার দিন ·'],['Demo checkout does not collect payment. Connect a commerce backend and payment provider before launch.','এটি নমুনা চেকআউট—এখানে কোনো পেমেন্ট নেওয়া হয় না। চালুর আগে অনলাইন স্টোর ও পেমেন্ট ব্যবস্থা যুক্ত করুন।'],['Order received','অর্ডার গ্রহণ করা হয়েছে'],['Thanks for choosing a little care.','আপনার যত্নের সঙ্গী হওয়ার জন্য ধন্যবাদ।'],['Your demo order number is','আপনার নমুনা অর্ডার নম্বর'],['In the live store, a confirmation and tracking link will be emailed to you.','আসল স্টোরে অর্ডার কনফার্মেশন ও ট্র্যাকিং লিংক ইমেইলে পাঠানো হবে।'],['Back to the shop','পণ্যের পাতায় ফিরুন'],['Review submission will connect to your store platform.','রিভিউ জমা দেওয়ার ব্যবস্থা স্টোর প্ল্যাটফর্মের সঙ্গে যুক্ত হবে।'],['Account sign-in is ready to connect to your store platform.','অ্যাকাউন্ট সাইন-ইন স্টোর প্ল্যাটফর্মের সঙ্গে যুক্ত হবে।'],['Demo: order tracking will connect to fulfillment.','নমুনা: অর্ডার ট্র্যাকিং ডেলিভারি ব্যবস্থার সঙ্গে যুক্ত হবে।'],['You’re on the list — thanks for joining.','আপনাকে তালিকায় রাখা হয়েছে—সঙ্গে থাকার জন্য ধন্যবাদ।'],
['Pre-wash botanical scalp oil · 100 ml','চুল ধোয়ার আগের ভেষজ স্ক্যাল্প অয়েল · ১০০ মি.লি.'],['Lightweight smoothing oil · 50 ml','হালকা মসৃণতার তেল · ৫০ মি.লি.'],['A considered duo for wash day','চুল ধোয়ার দিনের যত্নের জুটি'],['Bestseller','জনপ্রিয়'],['Everyday care','দৈনন্দিন যত্ন'],['Save ৳410','৳৪১০ সাশ্রয়'],['Scalp Elixir','স্ক্যাল্প এলিক্সির'],['Soft Ends Oil','চুলের আগার যত্নের তেল'],['The Ritual Set','যত্নের জুটি'],['Add to bag +','ব্যাগে যোগ করুন +'],['Add to bag','ব্যাগে যোগ করুন'],['Product photograph','পণ্যের ছবি'],['★★★★★','★★★★★'],['Verified buyer','যাচাইকৃত ক্রেতা'],['Order tracking will connect to fulfillment.','অর্ডার ট্র্যাকিং ডেলিভারি ব্যবস্থার সঙ্গে যুক্ত হবে।'],
['Small-batch · Thoughtful ingredients · Made for real life','যত্নে তৈরি · ভেবেচিন্তে বাছা উপাদান · দৈনন্দিন জীবনের জন্য'],['Your five-minute reset.','নিজের জন্য পাঁচ মিনিট।'],['Five minutes, just for you.','পাঁচ মিনিট, শুধু আপনার জন্য।'],['Sign in','সাইন ইন'],['Your email address','আপনার ইমেইল ঠিকানা'],['Verified purchase','যাচাইকৃত ক্রয়']
['FAQ','জিজ্ঞাসা'],['Notes from the bathroom shelf','বাথরুমের তাক থেকে যত্নের কথা'],['Botanical hair care for everyday rituals. Thoughtful by nature, simple by design.','প্রতিদিনের চুলের যত্নে ভেষজ অনুষঙ্গ। প্রকৃতি থেকে বেছে নেওয়া, সহজভাবে সাজানো।'],['© 2026 Root Ritual ·','© ২০২৬ রুট রিচুয়াল ·'],
['“I like that the instructions are simple. Two minutes of massage and I\'m done.”','“নির্দেশনা একদম সহজ। দুই মিনিট ম্যাসাজ করলেই হয়ে যায়।”'],['“A thoughtful gift for my sister—and she has already asked me to order another.”','“বোনকে উপহার দিয়েছিলাম—এখন আরেকটা অর্ডার করতে বলছে।”'],['SAMIRA · VERIFIED BUYER','সামিরা · যাচাইকৃত ক্রেতা'],['RUPA · VERIFIED BUYER','রূপা · যাচাইকৃত ক্রেতা'],['MEHREEN · VERIFIED BUYER','মেহরীন · যাচাইকৃত ক্রেতা'],
['Root Ritual স্ক্যাল্প এলিক্সির botanical hair oil with rosemary on warm limestone','উষ্ণ পাথরের ওপর রোজমেরির পাশে রুট রিচুয়াল স্ক্যাল্প এলিক্সির'],['Open menu','মেনু খুলুন'],['Email','ইমেইল'],['আপনার ইমেইল','আপনার ইমেইল ঠিকানা'],['01XXXXXXXXX','০১XXXXXXXXX'],
['What would you most like to focus on?','আপনি কোন বিষয়ে বেশি যত্ন নিতে চান?'],['A dry or tight-feeling scalp','শুষ্ক বা টানটান স্ক্যাল্প'],['Soft, smoother lengths','নরম ও মসৃণ চুল'],['A little of everything','সবকিছুরই একটু যত্ন'],['How would you describe your hair?','আপনার চুলের ধরন কেমন?'],['Fine or easily weighed down','পাতলা, সহজে তেলতেলে বা ভারী লাগে'],['Wavy, curly, or coily','ঢেউখেলানো, কোঁকড়া বা কুণ্ডলী চুল'],['Thick or textured','ঘন বা বিশেষ টেক্সচারের চুল'],['How often do you wash?','সাধারণত কত ঘন ঘন চুল ধোন?'],['Every day or two','প্রতিদিন বা এক দিন পরপর'],['A few times a week','সপ্তাহে কয়েকবার'],['About once a week','সপ্তাহে প্রায় একবার'],['of ${questions.length}','এর মধ্যে ${questions.length}'],['Start with','শুরু করতে পারেন'],['once weekly. Apply a small amount, see how your hair responds, and adjust your routine from there.','সপ্তাহে একবার ব্যবহার করে দেখুন। অল্প তেল দিয়ে শুরু করুন, চুলের প্রতিক্রিয়া বুঝে রুটিন ঠিক করুন।'],
['““বোতলটা তাকের ওপর দারুণ লাগে, আর চুল ধোয়ার আগে তেলটা ব্যবহার করতেও ভালো লাগে।””','“বোতলটা তাকের ওপর দারুণ লাগে, আর চুল ধোয়ার আগে তেলটা ব্যবহার করতেও ভালো লাগে।”']
];
let misses=[];for(let i=0;i<pairs.length;i++){if(!pairs[i])continue;const a=pairs[i][0],b=pairs[i][1];if(!s.includes(a))misses.push(a);s=s.split(a).join(b)}
s=s.replace("'en-BD'","'bn-BD'").replace("n.toLocaleString('en-BD')","n.toLocaleString('bn-BD')").replace("Math.floor(10000+Math.random()*89999)","Math.floor(10000+Math.random()*89999).toLocaleString('bn-BD')");
s=s.replace('value="Bangladesh"','value="Bangladesh"').replace('Order tracking connects when the fulfillment platform is configured.','অর্ডার পাঠানোর ব্যবস্থা যুক্ত হলে ট্র্যাকিং চালু হবে।');
fs.writeFileSync(p,s,'utf8');console.log('Updated; unmatched phrases:',misses.length,misses.slice(0,18));
